---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trunk-based
  namespace: todo
  labels:
    app: trunk-based
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trunk-based
  template:
    metadata:
      labels:
        app: trunk-based
    spec:
      containers:
      - name: trunk-based
        image: adesso/trunk-based:todo
        env:
        - name: VERSION
          value: "todo"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /trunk-based/resources/health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: trunk-based
  namespace: todo
spec:
  selector:
    app: trunk-based
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: todo
  type: NodePort
